//USER REDUCER
 export const SET_AUTHONTICATED = "SET_AUTHONTICATED"
 export const SET_UNAUTHONTIFICATED = "SET_UNAUTHONTIFICATED"
 export const SET_USER = "SET_USER"
 export const LOADING_USER = "LOADING_USER"
// UI REDUCERS
export const SET_ERRORS = "SET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_UI = "LOADING_UI"
//data

